### ISSUE TITLE
Update site not consumeable by tycho

### ISSUE THREAD

**Issue by ckulla** [kbirken/dbus-emf-model#7]
I recently had to change the location of the dbus emf model site in our target platform from googlecode to github. Later gave the following error in my tycho based build:

00:00:13.993 [ERROR] Partial IU: model.emf.dbusxml.edit
00:00:13.993 [ERROR] Partial IU: model.emf.dbusxml
00:00:13.993 [ERROR] Partial IU: model.emf.dbusxml
00:00:13.993 [ERROR] Partial IU: model.emf.dbusxml.editor
00:00:13.993 [ERROR] Partial IU: model.emf.dbusxml
00:00:13.994 [ERROR] Failed to resolve target definition /home/xxx.target: Failed to load p2 metadata repository from location http://kbirken.github.io/dbus-emf-model/releases/: The p2 repository at http://kbirken.github.io/dbus-emf-model/releases/ contains partial IUs (see above) from an old style update site which cannot be used for dependency resolution -> [Help 1]
 master

Using the update site from Eclipse works like a charm.

**Comment by ckulla** [comment]
See pull request #8

**Comment by kbirken** [comment]
Merged pull request and released with 0.8.1.
